services:
  # ================================
  # Next.js Application
  # ================================
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: real-estate-nextjs
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Next.js
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

      # NextAuth
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

      # Django API
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000/api/v1}
      - API_SECRET_KEY=${API_SECRET_KEY}

      # Mercado Pago
      - NEXT_PUBLIC_MP_PUBLIC_KEY=${NEXT_PUBLIC_MP_PUBLIC_KEY}
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
    networks:
      - real-estate-network
    volumes:
      # Persist logs (opcional)
      - ./logs:/app/logs

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  real-estate-network:
    name: real-estate-app-network
    driver: bridge

